### ISSUE TITLE
Todo by thursday

### ISSUE THREAD

**Issue by marineb** [nypublicradio/archived-design-system#20]
- [x] Update page title
- [x] Update favicon
- [x] Add color variables
- [x] Redo grid 
- [x] Fix links in link section
- [x] Add play icon to listen buttons
- [x] Fix columns so they show px widths
- [x] Remove 'introduction' to give more room to templates?
- [x] Fix all color variables in color scss
